{{ $repo := or .repo "http://http.kali.org/kali" }}
{{ $extra_components := or .extra_components "non-free contrib" }}
architecture: {{ .architecture }}

actions:
    # Add Kali repository and disable GPG check temporarily
  - action: run
    description: Prepare installing the keyring
    chroot: true
    command: echo "deb [trusted=yes] {{ $repo }} kali-rolling main {{ $extra_components }}" > /etc/apt/sources.list.d/kali.list

    # Install the Kali keyring
  - action: apt
    packages:
      - gnupg
      - dirmngr

  - action: run
    description: Import Kali GPG key
    chroot: true
    command: wget -q -O - https://archive.kali.org/archive-key.asc | gpg --import && gpg --export ED444FF07D8D0BF6 > /etc/apt/trusted.gpg.d/kali-rolling.gpg

    # Update repository with GPG check enabled
  - action: run
    description: Add final Kali repository
    chroot: true
    command: echo "deb {{ $repo }} kali-rolling main {{ $extra_components }}" > /etc/apt/sources.list.d/kali.list

  - action: apt
    packages:
      - bash-completion
      - network-manager
      - vim
      - ofono
      - procps
      - ofono-scripts
      - locales
      - less
      - sudo
      - bluez
      - rfkill
      - dialog
      - console-setup
      - dropbear-bin
      - dropbear
      - iproute2
      - kali-linux-default

  - action: run
    description: Set hostname for Kali device
    chroot: true
    command: echo kali-device > /etc/hostname
